# config/rest-graph.yaml
development:
    app_id: '301051506641125'
    secret: '67c2a52e5d5f504a37df6fc7e8287afc'
    callback_host: 'http://localhost:3000/'
production:
    app_id: '301051506641125'
    secret: '67c2a52e5d5f504a37df6fc7e8287afc'
    callback_host: 'http://chickwall.herokuapp.com/'
